apiVersion: v1
kind: Service
metadata:
  name: ocl-renting
  labels:
    app: ocl-renting
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ocl-renting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocl-renting-deployment
  namespace: test-ocl
  labels:
    app: ocl-renting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocl-renting
  template:
    metadata:
      labels:
        app: ocl-renting
    spec:
      containers:
      - name: ocl-renting
        image: morganprr/ocl_renting:latest
        ports:
        - containerPort: 80