name: Build Push an Deploy Docker Image

on:
  push:
    branches: [ main ] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 

      # trying 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Trying 
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Trying 
      - name: Check
        uses: actions/checkout@v2

      # Trying 
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # context: ./sources
          # file: ./sources/Dockerfile
          context: .
          file: ./Dockerfile
          push: true
          # tags: ffranc95/calc:1.0.${{github.run_number}}
          tags: morganprr/ocl_renting-1:1.0.${{github.run_number}}

      # Trying 
      # - name: Build Docker image
      #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/d_ocl_renting:1.0.12 .  

      # Trying 
      # - name: Push Docker image to Docker Hub
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/d_ocl_renting:1.0.12

      - name: Generate Kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: echo "$KUBECONFIG" > kubeconfig.yaml

      - name: Deploy image on Kubernetes
        run: kubectl apply -f ocl.yaml -n test-ocl --kubeconfig=kubeconfig.yaml 

      - name: 
        run: kubectl get services -n test-ocl -l app=ocl-renting  --kubeconfig=kubeconfig.yaml
    
      - name: Clean-Up
        run: rm kubeconfig.yaml