name: Build Push an Deploy Docker Image

on:
  push:
    branches: [ main ] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 

      - name: Login to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ocl_renting:1.0.12 .  

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ocl_renting:1.0.12

      - name: Generate Kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: echo "$KUBECONFIG" > kubeconfig.yaml

      # Try: 
      - name: Create namespace 
        run: kubectl create ns hello-app

      - name: Deploy image on Kubernetes
        run: kubectl apply -f ocl.yaml -n test_ocl --kubeconfig=kubeconfig.yaml 

      - name: 
        run: kubectl get services -n test_ocl -l app=ocl_renting  --kubeconfig=kubeconfig.yaml
    
      - name: Clean-Up
        run: rm kubeconfig.yaml