name: DockerHub CI / OVH CD

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # context: .
          file: Dockerfile
          push: true
          tags: morganprr/ocl_renting:1.0.${{github.run_number}}

# name: Deploy on OVH
      - name: Container deploy OVH 
        uses: ./.github/actions/docker-ovh-deploy
        with:
          # ssh_username: ${{ secrets.OVH_SSH_USERNAME }}
          # ssh_host: ${{ secrets.OVH_SSH_HOST }}
          ssh_private_key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
          registry: ${{ secrets.OVH_REGISTRY_ENDPOINT }}
          username: ${{ secrets.OVH_USERNAME }}
          password: ${{ secrets.OVH_PASSWORD }}
          image_name: ocl

# steps:
#       # - 
#       #   name: Set up QEMU
#       #   uses: docker/setup-qemu-action@v2
#       -
#         # name: Set up Docker Buildx
#         # uses: docker/setup-buildx-action@v2
#       # -
#       #   name: Login to DockerHub
#       #   uses: docker/login-action@v2
#       #   with:
#       #     username: ${{ secrets.DOCKERHUB_USERNAME }}
#       #     password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - 
#         name: Check
#         uses: actions/checkout@v2
#       -      
#         name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           # context: ./sources
#           # file: ./sources/Dockerfile
#           context: .
#           file: ./Dockerfile
#           push: true
#           # tags: ffranc95/calc:1.0.${{github.run_number}}
#           tags: morganprr/ocl_renting:1.0.${{github.run_number}}

