name: DockerHub CI / OVH CD

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Afficher le répertoire de travail
        run: | 
          echo $PWD 
          ls -la

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # context: .
          file: Dockerfile
          push: true
          tags: morganprr/ocl_renting:1.0.${{github.run_number}}

      # - name: Deploy to OVH hosting
      #   uses: pitscher/ovh-deploy-hosting-action@v1
        env:
          OVH_HOSTING_USER: ${{ secrets.OVH_USERNAME }}
          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_PASSWORD }}
      #     # OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
      #     # OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
          OVH_HOSTING_DOMAIN: ssh user@51.68.94.113
          # OVH_HOSTING_DOMAIN: m7uad9.c1.sbg5.k8s.ovh.net
          # OVH_HOSTING_DOMAIN: sjraqy.nodes.c1.sbg5.k8s.ovh.net
      #     # OVH_HOSTING_DOMAIN: ssh.clusterXXX.hosting.ovh.net
          REPOSITORY_NAME: ocl_renting
          REPOSITORY_URL: https://github.com/morganprieur/ocl_renting.git
      #     # REPOSITORY_NAME: my-repo
      #     # REPOSITORY_URL: https://github.com/me/my-repo.git

      - name: Kubernetes Deployment
        uses: TanmoySG/k-deploy-action@v0.2.2-alpha
        with: 
          # kubeconfig: https://m7uad9.c1.sbg5.k8s.ovh.net/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
          kubeconfig: .github/workflows/config
          # kubeconfig: ~/config
          # kubeconfig: path/to/kubeconfig
          # kubeconfig: ${{ secrets.kubeconfig }}
          namespace: 'default'
          # manifest: path/to/resources/file


# # name: Deploy on OVH
      # - name: Container deploy OVH 
      #   uses: ./.github/actions/docker-ovh-deploy 
      #   with:
      #     # ssh_username: ${{ secrets.OVH_SSH_USERNAME }}
      #     # ssh_host: ${{ secrets.OVH_SSH_HOST }}
      #     ssh_private_key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
      #     registry: ${{ secrets.OVH_REGISTRY_ENDPOINT }}
      #     username: ${{ secrets.OVH_USERNAME }}
      #     password: ${{ secrets.OVH_PASSWORD }}
      #     image_name: ocl

# Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/ocl_renting/ocl_renting/.github/actions/docker-ovh-deploy'. Did you forget to run actions/checkout before running your local action? 

# steps:
#       # - 
#       #   name: Set up QEMU
#       #   uses: docker/setup-qemu-action@v2
#       -
#         # name: Set up Docker Buildx
#         # uses: docker/setup-buildx-action@v2
#       # -
#       #   name: Login to DockerHub
#       #   uses: docker/login-action@v2
#       #   with:
#       #     username: ${{ secrets.DOCKERHUB_USERNAME }}
#       #     password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - 
#         name: Check
#         uses: actions/checkout@v2
#       -      
#         name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           # context: ./sources
#           # file: ./sources/Dockerfile
#           context: .
#           file: ./Dockerfile
#           push: true
#           # tags: ffranc95/calc:1.0.${{github.run_number}}
#           tags: morganprr/ocl_renting:1.0.${{github.run_number}}

