# name: Update the container calculator
name: Update OCL renting

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # - 
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Check
        uses: actions/checkout@v2
      -      
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          # context: ./sources
          # file: ./sources/Dockerfile
          context: .
          file: ./Dockerfile
          push: true
          # tags: ffranc95/calc:1.0.${{github.run_number}}
          tags: morganprr/ocl_renting:1.0.${{github.run_number}}
