# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# name: Python application
name: OCL renting

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Set up Python 3.10
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        # python-version: "3.10"
        python-version: "3.11"
    - name: Test
      # run: cd ./sources && python -m unittest test_calc.py 
      run: pip install pytest && pytest --cov=. tests 
