name: Deploy to OVH

on:
  push:
    branches: [main]
      # - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Save Docker image to a tar file
      run: docker save myapp:latest -o myapp.tar

    - name: Copy Docker image to server
      run: scp -o StrictHostKeyChecking=no myapp.tar ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:~/myapp.tar

    - name: Load Docker image on server
      run: |
        ssh -o StrictHostKeyChecking=no ssh user@51.68.94.113 << 'EOF'
          docker load -i ~/myapp.tar
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 80:80 myapp:latest
        EOF

      # ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'